In [1]:
import pandas as pd

df = pd.DataFrame({
    "loan_intent":["PERSONAL", "EDUCATION"], 
    "person_income": [30000, 50000]
})
df = pd.get_dummies(df, columns=["loan_intent"])
df.head()

person_income  loan_intent_EDUCATION  loan_intent_PERSONAL
0          30000                  False                  True
1          50000                   True                 False

In [2]:
df.values

array([[30000, False, True],
       [50000, True, False]], dtype=object)

In [ ]:
import torch

# this will fail because df.values has dtype object. The reason is that one single numpy array needs to be the same type for all things 
X = torch.tensor(df.values, dtype=torch.float32)
print(X)

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint64, uint32, uint16, uint8, and bool.

In [14]:
df = pd.DataFrame({
    "loan_intent":["PERSONAL", "EDUCATION"], 
    "person_income": [30000, 50000]
})
df = pd.get_dummies(df, columns=["loan_intent"]).astype(dtype="float32")
print(df.values)

#this will work now
X = torch.tensor(df.values, dtype=torch.float32)
print(X)

[[3.e+04 0.e+00 1.e+00]
 [5.e+04 1.e+00 0.e+00]]
tensor([[3.0000e+04, 0.0000e+00, 1.0000e+00],
        [5.0000e+04, 1.0000e+00, 0.0000e+00]])
